### ISSUE TITLE
Polymorphic relations

### ISSUE THREAD

**Issue by dohomi** [graphcool/prisma#54] opened 2016-12-21 21:56 UTC
Hi Guys,
in a CMS you probably would like to have an array of various content types declared as a schema inside of a parent schema:
```
-- Page
  -- title (string)
  -- slug (string|unique)
  -- contentElements (relation|1:n)
    --> currently only one schema is possible in the dropdown..
    --> multi-selection of allowed schema types would be a great improvement
```
I do miss this kind of setup in the current backend. I found out that its possible with a workaround but it feels rather inconvenient, from the editor point of view and for the developer.
Cheers

**Comment by sorenbs** [comment] 2017-03-03 17:41
Hi @dohomi The way we would support this is with GraphQL interfaces. It would allow you to write a query in the following ways:

```graphql
Page(slug:"cool-post"){
    photos: contentElements(filter: {__typename: "Photo"}){
      ... on Photo {
        url
      }
    }
    messages: contentElements(filter: {__typename: "Message"}){
      ... on Message {
        text
      }
    }
  }
```

or

```graphql
Page(slug:"cool-post"){
  contentElements{
  __typename
    ... on Photo {
      url
    }
    ... on Message {
      text
    }
  }
}
```

You can read more about this here http://graphql.org/learn/queries/#inline-fragments

Would this be a compelling solution to you?

**Comment by dohomi** [comment] 2017-03-04 05:50
@sorenbs yes that would be a great fit!

**Comment by dtuite** [comment] 2017-08-07 09:20
Just to add a use case I'm experiencing at the moment. In a social network type application, lots of things can be "liked". To implement this right now I believe I need multiple tables `Thing1Likes`, `Thing2Likes` and so on.

**Comment by sorenbs** [comment] 2018-03-30 01:25
Duplicate of https://github.com/graphcool/prisma/issues/83

**Closed by sorenbs** 2018-03-30 01:25 UTC
Labels: area/datamodel, kind/feature, proposal/needs-spec
