### ISSUE TITLE
Wrong schema on anonimous/incomplete relations

### ISSUE THREAD

**Issue by Fi1osof** [graphcool/prisma#1917] opened 2018-02-15 22:58 UTC
# Bug Report
prisma/1.2.3 (linux-x64) node-v9.5.0

Model:
```
type Call {
  id: ID! @unique
  status: CallStatus!
  created_at: DateTime!
  edited_at: DateTime
  created_by: User! @relation(name: "CallRequester")
  members: [User!]! @relation(name: "CallMembers")
  bills: [Bill!]!
}

enum BillStatus{
  Created
  Billed
  Paying
  Payed
}

type Bill{
  id: ID! @unique
  sum: Float!
  payer: User! @relation(name: "UserBills")
  start_date: DateTime!
  end_date: DateTime
  status: BillStatus!
  transactions: [PaymentTransaction!]! @relation(name: "BillTransaction")
  calls: [Call!]!
}

type PaymentTransaction{
  id: ID! @unique
  start_date: DateTime!
  bill: Bill! @relation(name: "BillTransaction")
}
```
Some time after generation i got same UpdateInput: http://joxi.ru/LmGyqplHRE4d3A
```
updateBill{
    where: {
        ...
    }
    data: {
        where: {
            ....
        }
        data: {
            ....
        }
    }
}
```
It's hard to reproduce, but fix with creating complete type-to-type named relations.

**Comment by Fi1osof** [comment] 2018-02-15 23:10
Same error...
```
updateService(
    data: ServiceUpdateInput!
    where: ServiceWhereUniqueInput!
): Service

type ServiceUpdateInput {
    where: ServiceWhereUniqueInput!
    data: ServiceUpdateDataInput!
}
```

Model:
```
type Service {
  id: ID! @unique
  name: String!
  description: String
  unit: String
  active: IsActive @default(value: "Yes")
}

type UserService{
  id: ID! @unique
  user: User!
  service: Service!
  price: Float!
  active: IsActive @default(value: "Yes")
}
```

Fixed with relations
usersServices: [UserService!]! @relation(name: "UserServicesService")
service: Service! @relation(name: "UserServicesService")

**Comment by do4gr** [comment] 2018-02-16 15:52
Thanks for reporting this. The issue is already fixed on the beta channel. See here: https://github.com/graphcool/prisma/issues/1909

I'm leaving this issue open until it is in the unstable channel

**Comment by Fi1osof** [comment] 2018-02-16 19:05
@do4gr Thanks! It's realy insidious bug))

**Closed** 2018-03-02 15:19 UTC
