### ISSUE TITLE
Updating field from String to Relation or vice versa with existing nodes introduces inconsistencies

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma#1944] opened 2018-02-20 09:43 UTC
# Bug Report

**Reproduction A**

I have not looked into a reproduction myself, but this is what I know:

> I changed type from string to relationship and forgot about one record inside so it got stuck

**Reproduction B**

Updating a relational field called `item` from type `Item` to `String` works, but introduces inconsistencies in the database schema. This might result in an internal server error for certain mutations.

**Comment by do4gr** [comment] 2018-05-05 12:59
I believe we fixed this when we added validations for Deploy operations. I cannot reproduce it anymore but added some tests covering this anyway to https://github.com/graphcool/prisma/pull/2334. I'm closing this, if anyone still runs into this problem please comment with a detailed reproduction.

**Closed by do4gr** 2018-05-05 12:59 UTC
Labels: area/deploy, kind/bug
