### ISSUE TITLE
Migration stuck in infinite loop when adding a second @unique variable to model

### ISSUE THREAD

**Issue by mfts** [graphcool/prisma#2121] opened 2018-03-20 14:29 UTC
# Bug Report

## Current behavior
On `prisma deploy` the terminal is stuck in an infinite loop. 
Interestingly, the logs in terminal don't mention that the `date` field is a `unique` field.

![screen shot 2018-03-20 at 15 16 47](https://user-images.githubusercontent.com/4049052/37660357-8b81fa4e-2c52-11e8-8f34-06a4cf2e9943.png)

## Reproduction
**I changed the model from:**
```
type CapacityShortage {
  startDate: DateTime!
  endDate: DateTime!
  id: ID! @unique
}
```
**to:**
```
type CapacityShortage {
  date: DateTime! @unique
  id: ID! @unique
}
```

I believe that the issue is with `@unique` on the `date` variable because when I removed it, it completed the migration as expected. 
After adding the `@unique` again and running `prisma deploy` it was again stuck in a loop and didn't perform the migration.

## Expected behavior?
Complete the migration from old to new model schema with generated prisma files also updated.

**Comment by mfts** [comment] 2018-04-09 12:30
@marktani I have an update on this:

```
type Phase {
  amount: Float!
  end: DateTime!
  id: ID! @unique
  machine: Machine @relation(name: "MachineOnPhase")
  start: DateTime!
  type: String!
  duration: Float!
  logId: Int! @unique    <---- adding @unique here
}
```

Running `prisma deploy` after adding the `@unique` directive didn't update **prisma.graphql** and **prisma.ts** as expected. 

After checking **prisma.graphql** didn't update the `PhaseWhereUniqueInput` input 
```
input PhaseWhereUniqueInput {
  id: ID
}
```

I expected it to be 
```
input PhaseWhereUniqueInput {
  id: ID
  logId: Int
}
```
or at least some sort of warning in the console that it wasn't updated... 
See console output: 
```
$ prisma deploy
Deploying service `shift-backend` to stage `dev` on cluster `michael/hb-kamax` 825ms

Changes:

  Phase (Type)
  ~ Updated field `logId`. It became unique.

Applying changes 1.7s

Your GraphQL database endpoint is live:

  HTTP:  https://hb-kamax_michael.prisma.sh/shift-backend/dev
  WS:    https://hb-kamax_michael.prisma.sh/shift-backend/dev


Hooks:
Checking, if schema file changed 836ms
```

**Comment by do4gr** [comment] 2018-05-07 16:19
Hey @mfts , 

sorry for getting back so late to you. I am looking at this issue now and your problems sound like there might already have been data that would violate the unique constraint. We are implementing checks to catch this up front, but it would be nice to know whether this could have been the case for you. Do you remember whether you already had data when that problem occurred?

**Comment by do4gr** [comment] 2018-05-07 16:46
Setting a  unique constraint will error if there are already duplicates present in the case of a field update or if a new field is required and unique since SQL will set default values for the newly required fields. I'm closing this issue since it seems to show symptoms of this problem. With the deploy changes from 1.6.1 and this PR the issue should be fixed https://github.com/graphcool/prisma/pull/2371 
If anyone is still experiencing problems please open a new issue with a reproduction.

**Closed** 2018-05-09 13:57 UTC
Labels: area/deploy, kind/bug
