### ISSUE TITLE
Degraded performance and error logs

### ISSUE THREAD

**Issue by divyenduz** [graphcool/prisma#1779] opened 2018-01-30 13:27 UTC
**Current behavior**
Prisma is talking a lot of CPU resources on DO (10$ instance, running both Prisma+Yoga). Virtually no traffic, very little data. 

I am getting the following message continuously in error logs

```
prisma-database_1  | [Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
prisma-database_1  | [Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
prisma-database_1  | {"@timestamp":"2018-01-29T20:31:18.870+00:00","@version":1,"message":"{\"key\":\"request/new\",\"requestId\":\"api:api:cjd0o5zyugt390182qel3ny9f\"}","logger_name":"com.prisma.api.server.ApiServer","thread_name":"single-server-akka.actor.default-dispatcher-4","level":"INFO","level_value":20000,"HOSTNAME":"553834c88022"}
prisma-database_1  | [Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
prisma-database_1  | [Metrics] Warning: Metric SystemShared.sqlQueryTimer not enough / too many custom tag values given at recording time to fill the defined tags WrappedArray(CustomTag(projectId,1000), CustomTag(queryName,1000)). Ignoring custom tags.
```

It is a stream of the same thing (about 5 GB of error logs in 12 hours)! I am able to get this error log on my local as well. 

P.S. I had used this to setup deployment. 
https://www.prismagraphql.com/docs/tutorials/cluster-deployment/digital-ocean-(manual)-texoo6aemu

**Reproduction**
Not sure yet. Could this be related to my schema?
How should I proceed to get a reproduction of this issue. 

**Expected behavior?**

Prisma should not emit such a frequency of logs and take less CPU.

**Comment by dpetrick** [comment] 2018-01-30 14:01
Fix for metrics logging merged in [this commit](https://github.com/graphcool/prisma/commit/4102030dc52853bf05fc922d282188d9134be405).
Memory management fix (which might cause spiking CPU due to frequently triggered garbage collection) also merged in the CLI. 
Both will be in the next release.

**Comment by divyenduz** [comment] 2018-01-30 14:14
Awesome! Thanks for the prompt response. 

Adding more information. This is the CPU graph (2 outages) which looks like a leak. I think this is the fix you are talking about. 

<img width="405" alt="screen shot 2018-01-30 at 7 41 32 pm" src="https://user-images.githubusercontent.com/746482/35570656-dc53f7b6-05f5-11e8-84b9-8f554e567f3d.png">

Any ETA on the next release yet?

**Comment by marktani** [comment] 2018-01-30 14:15
Soon™ ;)

**Comment by divyenduz** [comment] 2018-01-30 14:15
Also, to get around this issue until the next release, is there a way to do `reload` gracefully? 
https://github.com/graphcool/prisma/issues/1782

**Comment by marktani** [comment] 2018-01-31 21:46
Hey @divyenduz, I could reproduce the logging issues on `1.0.11` and resolved it by upgrading to `1.1.2`:

```
npm install -g prisma
prisma local upgrade
```

You can try adjusting the env var `JAVA_OPTS` to `-Xmx1G` limit the heap to 1GB, more information [in the release notes](https://github.com/graphcool/prisma/releases/tag/1.1.2).

Does that help with the CPU patterns you observed before?

**Comment by divyenduz** [comment] 2018-02-01 04:14
@marktani : Thanks for the update. Let me try the upgrade and `JAVA_OPTS`
Are there any reproduction steps that you followed?

**Comment by divyenduz** [comment] 2018-02-01 05:40
Did the upgrade! Will monitor the results. The `JAVA_OPTS` look to be at 1GB already. But are there supposed to be this many processes running for it?

<img width="1243" alt="screen shot 2018-02-01 at 11 08 35 am" src="https://user-images.githubusercontent.com/746482/35662849-6658ded6-0740-11e8-8a8e-0927b08992b4.png">

**Comment by divyenduz** [comment] 2018-02-01 16:57
Also, CPU still seems to be going up continuously (albeit slower than before). 

<img width="387" alt="screen shot 2018-02-01 at 10 21 17 pm" src="https://user-images.githubusercontent.com/746482/35691445-82b6c116-079e-11e8-964d-24586e6aa32e.png">

1 - Where I did the upgrade 

2 - Where I did `prisma local stop` and `prisma local start`

These are the outputs of `prisma --version` and `prisma cluster list`, confirming that upgrade has worked. 

```
root@ubuntu-s-1vcpu-2gb-fra1-01:~# prisma --version
prisma/1.1.2 (linux-x64) node-v8.4.0
root@ubuntu-s-1vcpu-2gb-fra1-01:~# prisma cluster list
name        version  endpoint
──────────  ───────  ─────────────────────────────
local       1.1.0    http://localhost:4466/cluster
prisma-eu1  1.1.0    https://eu1.prisma.sh/cluster
prisma-us1  1.1.0    https://us1.prisma.sh/cluster
root@ubuntu-s-1vcpu-2gb-fra1-01:~#
root@ubuntu-s-1vcpu-2gb-fra1-01:~#
```

And here is a snapshot of `htop`. Notice the high load average. 

<img width="1243" alt="screen shot 2018-02-01 at 10 26 35 pm" src="https://user-images.githubusercontent.com/746482/35691666-0f58b444-079f-11e8-8644-beb22abb38a5.png">

Do you think running it on a multi-core system will be better? 

Thanks

**Comment by divyenduz** [comment] 2018-02-02 18:52
Update!

Based on more discussions with @dpetrick and @marktani, I have a strong feeling that this might be happening on application server side (graphql-yoga, prisma-bindings or my custom code). 

Here is why I feel that! (extending the graph from above)

<img width="425" alt="screen shot 2018-02-02 at 11 09 43 pm" src="https://user-images.githubusercontent.com/746482/35749235-f38f384a-0876-11e8-9b74-8c19c51601a2.png">

1. Is where I did prisma upgrade, cli to 1.1.2, cluster to 1.1.0
2. Is where I did `prisma local stop` and `prisma local start`
3. Is where I restart the `graphql-yoga` process - CPU went down
4. I did a random application server (graphql-yoga and co) restart to see the behavior of the server and viola - CPU went down.

Now, this does not mean that the problem is absolutely not in Prisma part and absolutely yes in application server but this means that we need to profile more parts of the system. 

A few approaches:-

1. Test in production - I am setting up `newrelic`. 
2. Test on local with `ab` - soon to follow after production profiling setup.
3. Setup `graphql-yoga` and Prisma on separate DO servers and observe the behavior - will do this if 1,2 do not work.

If anyone has more ideas/better ideas/better tool suggestions! I am all ears. 

Thanks!

**Comment by divyenduz** [comment] 2018-02-03 19:12
Update! 

I used `ab` to benchmark prisma and application server (graphql-yoga and co) separately. 

All of this testing happened on my local with RAM of 8 GB. Prisma running on default JVM options.  

I observed that running a heavy workload on Prisma directly multiple times does not break it.  (prisma.txt contains POST payload)
```
ab -p prisma.txt -T application/json -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNlcnZpY2UiOiJncmFwaHFsLWtvY2tzQGRldiIsInJvbGVzIjpbImFkbWluIl19LCJpYXQiOjE1MTc2NDU2NTEsImV4cCI6MTUxODI1MDQ1MX0.xrtpaJ3RRX01oV7nncI4vLoJ90GC9_fY8qk_zH9eaz4' -c 100 -n 10000 "http://localhost:4466/graphql-kocks/dev"
``` 

But a much smaller workload on application server (graphql-yoga and co), makes Prisma backend respond with the following error (this starts around 900-ish request and continues thereafter)

```
[Network error]: FetchError: request to http://localhost:4466/graphql-kocks/dev failed, reason: read ECONNRESET
```

Workload on app server. 
```
ab -p yoga.txt -T application/json -c 20 -n 1000 "http://localhost:4000/"
```

And as soon as I restart the app server (note that in whole process I never restart Prisma cluster), Prisma starts to respond again. 

My hunch is that `prisma-binding` is not releasing the connections to Prisma. 

But I need to validate the node app server part. I am looking at various tools (have already setup newrelic in production) like nodejs-dashboard.

Can use help in identifying/validating the issue. 

Thanks!

**Comment by divyenduz** [comment] 2018-02-04 05:33
Update!

Output of `lsof -i tcp:4466 -n -P`

```
node    41877 divyendusingh  250u  IPv4 0xd769a198ca86b605      0t0  TCP 127.0.0.1:52004->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  251u  IPv4 0xd769a198caf7ef65      0t0  TCP 127.0.0.1:52707->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  252u  IPv4 0xd769a198cb074b85      0t0  TCP 127.0.0.1:52712->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  253u  IPv4 0xd769a198cb40e605      0t0  TCP 127.0.0.1:52713->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  254u  IPv4 0xd769a198cc3cfb85      0t0  TCP 127.0.0.1:51946->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  255u  IPv4 0xd769a198c29fd225      0t0  TCP 127.0.0.1:52738->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  256u  IPv4 0xd769a198cae28605      0t0  TCP 127.0.0.1:52739->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  257u  IPv4 0xd769a198cb0f4b85      0t0  TCP 127.0.0.1:52740->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  258u  IPv4 0xd769a198cb6d6605      0t0  TCP 127.0.0.1:52733->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  259u  IPv4 0xd769a198caca9b85      0t0  TCP 127.0.0.1:52240->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  260u  IPv4 0xd769a198cbde2b85      0t0  TCP 127.0.0.1:52734->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  261u  IPv4 0xd769a198cb73a225      0t0  TCP 127.0.0.1:52090->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  262u  IPv4 0xd769a198cb4628c5      0t0  TCP 127.0.0.1:52735->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  263u  IPv4 0xd769a198cab33f65      0t0  TCP 127.0.0.1:52736->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  265u  IPv4 0xd769a198c3954f65      0t0  TCP 127.0.0.1:52091->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  276u  IPv4 0xd769a198cc7b1225      0t0  TCP 127.0.0.1:51829->127.0.0.1:4466 (ESTABLISHED)
node    41877 divyendusingh  284u  IPv4 0xd769a198c92d0605      0t0  TCP 127.0.0.1:51956->127.0.0.1:4466 (ESTABLISHED)
```
More of the same (about 1000), truncated for brevity. 

Looks like it is not releasing the connecting to Prisma service at `4466` and Prisma starts to reject the connections after a limit. 

Also, output of `lsof -i tcp:3307 -n -P` (3307 is my Prisma DB port) returns just two rows, which means that Prisma is able to release internal MySQL connection. 

```
divyendusingh [prisma-backend]$ lsof -i tcp:3307 -n -P
COMMAND  PID          USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
vpnkit  1349 divyendusingh   21u  IPv4 0xd769a198bd8b2225      0t0  TCP *:3307 (LISTEN)
vpnkit  1349 divyendusingh   22u  IPv6 0xd769a198bc20561d      0t0  TCP [::1]:3307 (LISTEN)
```

At this moment, Prisma service uptime is limited and running an `ab` test on it directly results in errors. 

But restarting the application server (I believe releases the Prisma connections) makes Prisma service come online and take a full hammering from `ab`. 

I am currently trying to [locate the part of codebase](https://github.com/graphcool/prisma-binding/blob/8e7d45d70ebb470d8d25b960b516918f3a4c93d9/src/link.ts#L18) using the Prisma endpoint and if it is possible to release this connection gracefully. 

Any help on how to proceed from here? That will speed up the process for me manifolds. 🙏 

Thanks 👍

**Comment by maxdarque** [comment] 2018-02-04 12:06
Not sure if it is related but I'm also experiencing degraded performance using the public prisma cluster on `eu1.prisma.sh`. My graphql-yoga server is on AWS Lambda (using Apex Up). 

In my react app, I have a data-heavy page which runs ~10 queries. My permission system is fairly complex, so typically I have to run one or two checks on the user's permissions before running a query (typically a `ctx.db.exists` call). This means for my ~10 queries launched by the client side app (where I have batching set to 100ms on apollo-client), I'm launching maybe double to triple the number of queries from the server (20-30). 

If I simultaneously launch 10 browser tabs on the data-heavy page, a significant number of my AWS Lambda functions timeout after 18s. Opening 10 tabs, translates to roughly 250 prisma/db requests in the space of 5s. Any ideas? 

Using "prisma-binding": "^1.5.3" and "prisma": "^1.1.2", Converting my typescript to ES6 for AWS Lambda

**Comment by timsuchanek** [comment] 2018-02-07 13:44
Thanks to all everybody involved here! You did awesome detective work!
There was indeed a problem with the WebSocket connections, which were unnecessarily made by instantiating the `WebsocketLink`. I pushed a fix to `prisma-binding` that fixes this problem:
https://github.com/graphcool/prisma-binding/pull/93/files
It's released under `1.5.5`.
I'm closing this, for now, assuming that these performance problems are fixed. Reopen/comment if there are still problems.

**Closed by timsuchanek** 2018-02-07 13:44 UTC

**Comment by timsuchanek** [comment] 2018-02-07 13:51
There is one more thing to note though: When using Subscriptions, there is still a memory leak.
Connections are not aborted once they are not used anymore.
There is change needed in the `subscriptions-transport-ws`, you can look into this issue for the progress https://github.com/apollographql/subscriptions-transport-ws/issues/351

**Comment by maxdarque** [comment] 2018-02-10 12:12
I think my performance issues listed above might be related to the throttling on the public cluster

See issue [#1863](https://github.com/graphcool/prisma/issues/1863)
