### ISSUE TITLE
Prisma container crashes on AWS Fargate

### ISSUE THREAD

**Issue by cameronk** [graphcool/prisma#2023] opened 2018-03-06 04:12 UTC
# Bug Report

**Current behavior**

When running prisma:1.3 on AWS Fargate, the container crashes on boot.

**Reproduction**

1. Create a cluster in Amazon ECS
2. Create a new task definition 
3. Choose the FARGATE compatibility mode. Fill out env vars / etc. as necessary.
4. Save the task definition
5. Run the task with Launch type: FARGATE
6. View your container's logs.

Here's my logs:
```
Listening for transport dt_socket at address: 8000
Error: Exception thrown by the agent : java.net.MalformedURLException: Local host name unknown: java.net.UnknownHostException: 823064ca3923: 823064ca3923: System error
```

I believe this is because Fargate uses the `awsvpc` networking mode (exclusively), and Java is trying to attach a debugger to a host that doesn't exist. I tried adding a `-Djava.security.manager` flag to my `JAVA_OPTS` environment variable, but it doesn't seem to change anything. It's unclear if this is because (a) the debugger doesn't get disabled by that flag, or (b) the error isn't coming from a debugger.

Relevant articles:
https://stackoverflow.com/questions/38426043/application-prints-listening-for-transport-dt-socket-at-address-5005-and-does
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/introclientissues005.html
https://wiki.sei.cmu.edu/confluence/display/java/ENV05-J.+Do+not+deploy+an+application+that+can+be+remotely+monitored (see "Compliant solution")

**Expected behavior?**

The container should boot up.

**Comment by sirsavary** [comment] 2018-03-13 16:15
Would be really great if we could deploy to Fargate instead of one of the current options. The rest of our stack runs on AWS and it will be sorta weird to have Prisma deployed elsewhere.

**Comment by cameronk** [comment] 2018-03-13 22:01
@sirsavary Agreed, I'm in the same boat. I have the `graphql-yoga` server working on Fargate, but haven't been able to get `prisma` working yet. Forced to host it elsewhere in the meantime. Lack of scalability is worrisome.

**Comment by rush-levint** [comment] 2018-03-22 01:19
I'm looking for this option too.

**Comment by cameronk** [comment] 2018-03-29 03:07
@marktani Bumping this b/c it's a blocker for deploying Prisma to Fargate, which is a pretty solid solution for hosting containers, especially for those of us who are new to container orchestration and don't want to deal with hosting servers ourselves or running Kubernetes.

**Comment by dpetrick** [comment] 2018-04-04 13:58
Apologies for the delay, the issue is fixed on the latest beta branch (`1.6-beta` at the time of writing). Can you give it a spin and report back, please?

**Comment by sorenbs** [comment] 2018-04-04 15:52
This repository contains documentation for running Prisma on Fargate and connecting the CLI: https://github.com/graphcool/prisma-templates

**Comment by marktani** [comment] 2018-04-05 18:29
Thanks again for your feedback, @sirsavary @cameronk @rush-levint. We posted a tutorial for deploying a Prisma cluster on Fargate here: https://blog.graph.cool/how-to-deploy-a-prisma-cluster-to-aws-fargate-using-docker-cloudformation-293aa8727b89.

As mentioned in the article, the minimum Prisma version for this to work is 1.6 (beta).

**Closed by marktani** 2018-04-05 18:29 UTC
Labels: kind/question, triage/pending
