### ISSUE TITLE
Variable '$_where' cannot be non input type 'PostFilter'

### ISSUE THREAD

**Issue by terion-name** [graphcool/prisma#1682] opened 2018-01-18 17:26 UTC
**Current behavior**

Queries in basic demo app fail

<img width="1680" alt="2018-01-18 19 22 13" src="https://user-images.githubusercontent.com/1060205/35112040-7bc72766-fc85-11e7-8c19-babcc4f0662c.png">

**Reproduction**

* run `prisma init hello-world`
* setup a simple ts demo project with local cluster
* run `prisma deploy`
* run `yarn dev`
* go to playground and try to run a query

**Expected behavior?**

It works

**Comment by nikolasburk** [comment] 2018-01-25 09:08
Hey @terion-name, I'm not able to reproduce this problem. Which boilerplate were you using, `node-basic`? It might be that the issue already got fixed in the meantime! I'm closing the issue for now - if you can confirm this is still an issue for your please reply and I'll open the issue again 🙂

**Closed by nikolasburk** 2018-01-25 09:08 UTC

**Comment by coniel** [comment] 2018-03-29 12:56
I am getting a similar error with my own queries/mutations (queries/mutations which came with the boilerplate work fine). I created a forum post with the details: https://www.graph.cool/forum/t/prisma-boilerplate-existing-queries-mutations-work-but-my-own-do-not-error-variable-data-cannot-be-non-input-type-subjectcreateinput/2998
