### ISSUE TITLE
Duplicate "graphql"

### ISSUE THREAD

**Issue by tfiwm** [graphcool/prisma#1928] opened 2018-02-17 15:09 UTC
We had this problem inside graphql-yoga too but it was fixed. Now it looks like that we have it in prisma too

# Bug Report

**Current behavior**
```
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/graphql/jsutils/instanceOf.js:17:13)
    at isSchema (/Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/graphql/type/schema.js:48:35)
    at validateSchema (/Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/graphql/type/validate.js:51:25)
    at assertValidSchema (/Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/graphql/type/validate.js:76:16)
    at Object.validate (/Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/graphql/validation/validate.js:61:35)
    at doRunQuery (/Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/apollo-server-core/src/runQuery.ts:143:30)
    at /Users/mtschimev/ownCloud/private_workspace/visual-knight/visual-testing-manager/server/prisma/node_modules/apollo-server-core/src/runQuery.ts:69:39
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Reproduction**

Prisma project with following package.json
```
"dependencies": {
    "bcryptjs": "2.4.3",
    "dotenv": "5.0.0",
    "graphql-yoga": "1.3.2",
    "jsonwebtoken": "8.1.1",
    "prisma-binding": "1.5.12"
  },
  "devDependencies": {
    "@types/bcryptjs": "2.4.1",
    "dotenv-cli": "1.4.0",
    "graphql-cli": "2.14.1",
    "nodemon": "1.14.12",
    "npm-run-all": "4.1.2",
    "prisma": "1.2.3",
    "rimraf": "2.6.2",
    "ts-node": "4.1.0",
    "typescript": "2.6.2"
  }
```

**Expected behavior?**
Server is working ;)

**Comment by maarteNNNN** [comment] 2018-02-17 15:51
@tfiwm [Here was my issue](https://github.com/graphcool/prisma/issues/1924) downgrade your prisma to `1.1.2`
After a restart of all services it seemed to work again.
```
yarn add prisma@1.1.2
prisma local nuke
prisma local stop
prisma local start
prisma local deploy
yarn dev
```

**Comment by marktani** [comment] 2018-02-17 18:29
@tfiwm could you try using the global dependency for `prisma` instead?

**Comment by peterschussheim** [comment] 2018-02-17 19:43
I am getting similar errors:

```bash
Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/jsutils/instanceOf.js:17:13)
    at isSchema (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/type/schema.js:48:35)
    at validateSchema (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/type/validate.js:51:25)
    at assertValidSchema (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/type/validate.js:76:16)
    at Object.validate (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/graphql/validation/validate.js:61:35)
    at doRunQuery (/Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/apollo-server-core/src/runQuery.ts:143:30)
    at /Users/peter/Sources/Repos/notes/packages/notes-prisma-local/node_modules/apollo-server-core/src/runQuery.ts:69:39
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Please let me know if you want a new issue for this.

**Comment by lirbank** [comment] 2018-02-17 21:39
I was trying different setup options for prisma and see the same thing what ever I do (these are fresh installs).

Adding this to `package.json` solves the issue:

```json
"resolutions": {
  "graphql": "^0.13.1"
}
```

**Comment by tfiwm** [comment] 2018-02-17 22:18
@lirbank your solution works for me! Thx ;)

**Comment by iamclaytonray** [comment] 2018-02-18 00:03
For anyone who is using Yarn, this is a known issue between them & GraphQL. The simple workaround is to `rm -rf node_modules && npm i` to install with NPM. I'll try to find the issue to link here. Otherwise, this issue can probably be closed since it has nothing to do with GC/Prisma. 😄

**Comment by lirbank** [comment] 2018-02-18 03:59
@iamclaytonray Just a heads up before you close this issue - if you have yarn installed on your system and follow the steps here https://www.prismagraphql.com/docs/quickstart/ it happens every time (at least for me). You don't see it if you start fresh?

**Comment by iamclaytonray** [comment] 2018-02-18 04:04
I don't have access to close the issue but despite setting up Prisma a specific way, the issue is between Yarn and `graphql`

**Comment by muhajirframe** [comment] 2018-02-20 04:29
Yeah, seems the trouble was with yarn. @iamclaytonray . Your solution works for me..

**Comment by marktani** [comment] 2018-02-21 18:43
Hey @tfiwm @maarteNNNN @peterschussheim @lirbank @iamclaytonray, thanks for chiming in.

Could you please check if following [these instructions](https://github.com/graphcool/graphql-yoga/issues/162#issuecomment-367368045) solves the issue for you?

Thanks! 🙌

**Comment by schickling** [comment] 2018-02-21 19:40
As @lirbank pointed out, add the following to your `package.json` and run `yarn install`. This should fix the problem:

```json
  "resolutions": {
    "graphql": "0.13.1"
  }
```

Please let us know if someone still hits this problem.

**Closed by schickling** 2018-02-21 19:40 UTC
Labels: component/cli, kind/bug

**Comment by marktani** [comment] 2018-02-26 10:09
For anyone still running into this, upgrading `yarn` from `0.27.5` to `1.3.2` fixed it for me.

**Comment by LawJolla** [comment] 2018-04-04 20:10
And for anyone else fighting this one, I've found this error on port conflicts.  If the server didn't properly shut down and still holds the port, restarting the server will throw the port conflict error but will also throw the multiple version of GraphQL error, so you may never see the conflict.

To fix it (on a Mac), first find the offending process
`lsof -i :<port>`
Find the PID and..
`kill -9 <pid>`

**Comment by schickling** [comment] 2018-04-07 15:01
Quick tip to @LawJolla: Use https://github.com/sindresorhus/fkill-cli to make killing processes by port easier. 💯

**Comment by lynnic26** [comment] 2018-06-05 02:40
` "resolutions": {
    "graphql": "0.13.1"
  }`
adding resolutions works for me

**Comment by tomitrescak** [comment] 2018-07-09 13:16
Wow, I can;t believe that the only solution was to use NPM instead of yarn. I tried EVERYTHING, but that was the only thing that helped. Oh well, luckily npm is much faster now.

**Comment by tomitrescak** [comment] 2018-08-24 02:04
Is this considered to be solved? I cannot make it work in any of my applications ;( Only NPM works. Yarn is deaf. I have everything installed properly:

```
yarn global add graphql-cli graphql prisma-binding
```

I have following in my package.json

```
  "resolutions": {
    "graphql": "0.13.2"
  },
```

Yet still no love ;(

**Comment by sscaff1** [comment] 2018-10-25 13:22
I am still getting this issue. package.json
```
  "dependencies": {
    "dotenv": "^6.1.0",
    "graphql": "^0.13.2",
    "graphql-cli": "^2.16.7",
    "prisma": "^1.19.0",
    "prisma-binding": "2.1.6"
  },
  "resolutions": {
    "graphql": "^0.13.2"
  }
```
npm script
"get-schema": "graphql get-schema -p prisma --dotenv variables.env"

I've tried killing every process, uninstalling Yarn, installing everything with NPM. Nothing works. Frustrating...

**Comment by iquabius** [comment] 2018-10-27 10:16
I was getting this error running `npx prisma generate`. I was able to get around it by using the global prisma: `prisma generate`.

**Comment by AviIhej** [comment] 2018-11-10 02:54
I'm having the same problem as her and I'm running Docker. I have tried absolutely everything

**Comment by geabenitez** [comment] 2018-11-25 06:30
> rm -rf node_modules && npm i

This worked for me.

**Comment by jackgray** [comment] 2019-01-28 21:50
What I can't figure out is why this started happening to me since I have not changed any of my dependencies at all. Deleting the modules and reinstalling did not work and searching processes on my port returned nothing.

**Comment by yucheng94** [comment] 2019-01-30 17:45
> Wow, I can't believe that the only solution was to use NPM instead of yarn. I tried EVERYTHING, but that was the only thing that helped. Oh well, luckily npm is much faster now.

same

**Comment by Wgil** [comment] 2019-02-12 22:14
Downgrading to:
```
"prisma: ^1.17.1",
"graphql-cli: "^2.16.7"
```

solved this issue for me

**Comment by jackgray** [comment] 2019-02-15 22:50
@Wgil I'm not sure I consider downgrading to pre-prisma-client a solution.. We need to be able to use npm and the latest stable release of prisma imo. Yarn shouldn't be necessary as it is not always up to date with prisma, at least it wasn't the last time I used it, when I was trying to move from 1.17 to 1.18, at which point I had to delete yarn to let npm be prioritized globally. If yarn is required to use prisma without errors, would it be reasonable to state so in the docs?

**Comment by Wgil** [comment] 2019-02-17 18:30
@jackgray you're right. By the way, It also worked on npm...

**Comment by mszczepanczyk** [comment] 2019-06-09 18:08
I'm getting this error with 1.34. 1.33 worked fine (npm 6.4.1)

**Comment by thehashrocket** [comment] 2019-06-17 00:51
i solved this by doing `npm i -g prisma`. I was able to do `prisma init` after that and deploy.

**Comment by KShewengger** [comment] 2020-12-02 02:44
Combining with all the method specified above. 
What worked for me was:


1.) Delete your node_modules and your package-lock.json
```
$ rm -rf node_modules
$ rm package-lock.json
```

2.) On your `package.json`, add this 
```
{
   ...
   "resolutions": {
       "graphql": "^0.13.1"
  },
  "dependencies": {
       ...,
       "graphql": "^0.13.1"
  }
}
```

3.) Install all dependencies
`$ npm install` 

___
Current Global versions

Node version: **v14.14.0**
   - For Prisma 1, it's best to use v12.x.x especially when running `prisma init`

Prisma version: **v1.34.10**
