### ISSUE TITLE
How do we get generated files I.e prisma.graphql & prisma.ts - post 1.7

### ISSUE THREAD

**Issue by OGNeutron** [graphcool/prisma#2297] opened 2018-04-27 12:33 UTC
I haven't found a way to perform the same function which we had pre-1.7, that's one of the main features I really liked.

**Comment by mzygmunt** [comment] 2018-04-27 14:11
1. Install graphql-cli
```
npm i -g graphql-cli
```
2. Add post-deploy hook to prisma.yml:
```
hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project database
    - graphql prepare
```
3. Now you can execute 
```
prisma deploy
```

This is example .graphqlconfig.yml:
```
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:5000/graphql
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```

**Comment by frankdugan3** [comment] 2018-04-27 14:12
Also covered in the [upgrade guide](https://www.prisma.io/docs/reference/upgrade-guides/upgrading-prisma/upgrade-to-1.7-iquaecuj6b#download-the-prisma-graphql-schema-and-invoking-codegen).

**Comment by OGNeutron** [comment] 2018-04-27 14:43
Did that, still doesn't want to do it, I'll show mine if you want and it keeps saying 

Syntax Error: Unexpected Name "F"

```
projects:
  main_hub_app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```

```
endpoint: http://localhost:4466
datamodel: database/datamodel.graphql
hooks:
  post-deploy:
    # - echo "Deployment finished"
    - graphql get-schema --project prisma
    - graphql prepare
```

**Comment by OGNeutron** [comment] 2018-04-27 16:30
I found out the problem it seems the previous generated code was causing an error, once I removed them, it built new ones, but I doubt that's intended, but it seems you need to delete the old one first.

**Comment by FredyC** [comment] 2018-04-28 14:09
Docs seem to be strangely incomplete. There is a mention of these hooks in upgrade guide, but in actual [structure doc](https://www.prisma.io/docs/reference/service-configuration/prisma.yml/yaml-structure-ufeshusai8) there is not a word about it :)

**Comment by overpod** [comment] 2018-04-28 15:37
It is very difficult for me with a working project because of this

**Comment by overpod** [comment] 2018-04-30 04:31
```bash
$ cat .graphqlconfig.yml
projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```
```bash
$ cat database/prisma.yml
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.graphql
secret: ${env:PRISMA_SECRET}
hooks:
  post-deploy:
    - graphql get-schema --project prisma
    - graphql prepare
```
**Error**
```bash
$ prisma deploy
Deploying service `autoparts` to stage `dev` to server `default` 426ms
Service is already up to date.

post-deploy:
Running graphql get-schema --project prisma !
 !    "graphql" �� ���� ����७��� ��� ���譥�
 !    ��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
 !

Get in touch if you need help: https://www.graph.cool/forum
To get more detailed output, run $ export DEBUG="*"
```

**Comment by overpod** [comment] 2018-04-30 04:32
how do i generate files ?

**Comment by yoorw** [comment] 2018-04-30 06:54
Hello Everyone,

I am having the same issue, but I get a different Error Output. 

Below is my prisma.yml:
```secret: ${env:PRISMA_SECRET} 
datamodel: datamodel.graphql
seed:
  import: seed.graphql
endpoint: https://example-rds-aws_example.prisma.sh/example/example-project/dev
hooks: 
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project prisma
    - graphql prepare 
```

Below is my graphqlconfig.yml:
```projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  prisma: 
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      perpare-binding:
        output: generated/prisma.ts
        generator: prisma-ts
```
   

Below is the Error I receive: 
![hookspostdeployissue](https://user-images.githubusercontent.com/37107949/39417185-214e6d5c-4c18-11e8-995d-571f4fd7607f.jpg)

1) Why does CLI respond saying Invalide prisma.yml file?

2) After the v1.7.1 upgrade, I am not able to deploy because of the endpoint in prisma.yml 


Is there something I'm doing incorrectly?

**Comment by marktani** [comment] 2018-04-30 16:39
@FredyC: thanks for your feedback, we added docs [here](https://www.prisma.io/docs/reference/service-configuration/prisma.yml/yaml-structure-ufeshusai8#hooks-(optional)). Please create a new issue if you feel something in the documentation could be improved 🙂 

@overpod: syntactically, everything looks good to me. However, the error message could hint towards an encoding issue. Could you please create a new bug report, including a minimal setup for reproduction [here](https://github.com/graphcool/prisma/issues/new?template=bug.md)?

@yoorw: One part of your issue is being discussed here: https://www.graph.cool/forum/t/how-to-fix-invalid-prisma-yml-file-prisma-yml-should-not-have-additional-properties-additionalproperty-endpoint-errors/3303/2?u=nilan. And then, it looks like you are not setting the env variable `PRISMA_SECRET`, but you use it in your `prisma.yml` file.

I am closing this issue, as the original question is answered.

Please don't reply here, but create a new issue if you have further questions for your indivual problems.

**Closed by marktani** 2018-04-30 16:39 UTC
