### ISSUE TITLE
Can't see function log output in cli

### ISSUE THREAD

**Issue by ylac** [graphcool/prisma#1251] opened 2017-11-12 00:17 UTC
**Current behavior**
Clicking on output entry in function log displays a white square (Chrome) or scroll buttons (Firefox)  instead of expanding the output. Occurs on Win7 x64.

![function log output](https://user-images.githubusercontent.com/25894581/32694711-f55d5796-c79a-11e7-9b21-d527dc7a194d.png)

**Comment by kbrandwijk** [comment] 2017-11-12 00:38
Duplicate of https://github.com/graphcool/framework/issues/1073

**Closed** 2018-01-23 16:28 UTC
