### ISSUE TITLE
Intinite loop on deploy when adding @unique to column

### ISSUE THREAD

**Issue by attilah** [graphcool/prisma#1773] opened 2018-01-30 06:58 UTC
**Current behavior**

upon updating a schema in a specific way, deploy goes into infinite loop with a step

**Reproduction**

deploy this schema
```
type ContentProvider {
  id: ID! @unique
  type: ContentProviderType!
}

enum ContentProviderType {
  Twitter
}
```

insert 2 records with the Twitter type:
```
mutation {
  t1: createContentProvider( data: {
    type: Twitter
  }) {
    id
  }

  t2: createContentProvider( data: {
    type: Twitter
  }) {
    id
  }
}
```

update the schema by adding @unique to type field. This should cause SQL exception since the schema violates the existing data in the database.

```
type ContentProvider {
  id: ID! @unique
  type: ContentProviderType! @unique
}

enum ContentProviderType {
  Twitter
}
```

what I'm getting on console is repeated entries of these lines:
```
client Sending query to cluster local +505ms
  client http://localhost:4466/cluster +1ms
  client query ($name: String! $stage: String!) {
  client           migrationStatus(name: $name stage: $stage) {
  client             projectId
  client             revision
  client             status
  client             applied
  client             rolledBack
  client             errors
  client           }
  client         }
  client          +1ms
  client { stage: 'dev', name: 'foo' } +2ms
  client { migrationStatus:
  client    { rolledBack: 0,
  client      applied: 6,
  client      projectId: 'foo@dev',
  client      errors: [],
  client      revision: 2,
  client      status: 'SUCCESS' } } +20ms
```

**Expected behavior?**

Meaningful error message "translated" from the SQL error that this schema modification is not possible.

**Comment by do4gr** [comment] 2018-05-07 16:45
Setting a  unique constraint will error if there are already duplicates present in the case of a field update or if a new field is required and unique since SQL will set default values for the newly required fields. I'm closing this issue since it seems to show symptoms of this problem. With the deploy changes from 1.6.1 and this PR the issue should be fixed https://github.com/graphcool/prisma/pull/2371 
If anyone is still experiencing problems please open a new issue with a reproduction.

**Closed** 2018-05-09 13:57 UTC
Labels: area/deploy, kind/bug

**Comment by gregwebs** [comment] 2018-09-19 23:13
I am still able to make an infinite loop. This is a database configuration issue on my end, but errors show up for the Migration and requests are continually sent. An exit is expected rather than an infinite loop.

**Comment by marktani** [comment] 2018-09-20 08:37
Hi @gregwebs, please create a new issue in which you share a "before" and "after" version of your datamodel that causes the infinite loop. There are other known issues that cause this symptom collected here: #2018.

**Comment by gregwebs** [comment] 2018-09-20 17:07
My point is not that I have a particular case that causes an infinite loop, but that an infinite loop should not be possible. prisma appears to have an unbounded error retry in some error situations during deploy.
