### ISSUE TITLE
Stuck on deployment

### ISSUE THREAD

**Issue by blocka** [graphcool/prisma#1802] opened 2018-02-01 13:40 UTC
Before schema:

```
enum UserKind {
  User
  Partner
}

enum Country {
  US,
  IL
}

type User {
  id: ID! @unique
  firstName: String!
  lastName: String!
  email: String! @unique
  auth0id: String! @unique
  identity: String
  picture: String
  kind: UserKind @default(value: "User")
  timeline: [FeedItem!]!
  streamToken: String
  following: [User!]! @relation(name: "Following")
  followedBy: [User!]! @relation(name: "Follower") 
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Like {
  id: ID! @unique
  Item: FeedItem!
  User: User!
  createdAt: DateTime! 
  updatedAt: DateTime!
}

# Represent Feed item of specific type
# FeedItem could be connected to other entities, e.g. Opportunity, which enrich FeedItem with more details
# We could say that at some point, FeedItem will probably be connected to separate entities of at least following types: 
# - Opportunity (Activity / Event / Challenge / etc)
# - Photo Albums
# - Pools
# etc
# Note: while it is possible to use Meta field for that, in practice it makes sense to store such rich concepts as separate entities and use refs
# One of reasons: many feed items could be linked to same entity, e.g. many users can post things which relevant to same Opportunity, etc.
type FeedItem {
  id: ID! @unique
  type: String!  
  meta: Json
  author: User,
  verb: String!
  time: DateTime # this is time, when Feed item should appear in user timeline
  likes: Int
  liked_by_viewer: Boolean
  createdAt: DateTime! # created not always same as time (but usually is same), e.g. for cases when Post was scheduled, etc. 
  updatedAt: DateTime! # we want at some point to support edit and we need to know when it was done (if post scheduled, than edited time value could be different to 'time' property)
  Opportunity: Opportunity!
}

type Opportunity {
  id: ID! @unique
  author: User, # There can be only one author of Opportunity, usually it's Partner 
  name: String 
  description: String!
  location: String! # TODO: make separate location entity at some point and use refs  
  createdAt: DateTime! # When Opportunity was first created
  updatedAt: DateTime! # When Opportunity was edited last time
  publishedAt: DateTime! # Some Opportunities are not published right away, we want to know when it was first published on site (made public)
  startsAt: DateTime! # Some Opportunities, e.g. Events, can have start time (if value is null it means Opportunity happens now)
  endsAt: DateTime! # Some Opportunities, e.g. Events, usually have end time (if value is null it means Opportunity happens now or users can enjoy it any time in the future)  
}
```

After schema:

Just adding
```
type Picture {
  url: String!
}
```

**Comment by akoenig** [comment] 2018-02-13 06:22
@blocka Could you shed some light on this? Some additional information would be useful. Things like:

  * Which version of Prisma?
  * Do you deploy to `local` or the `dev` cluster?

**Comment by blocka** [comment] 2018-02-13 12:04
The version of prisma is 1.1.2
We are deploying it to a prisma cluster we are hosting on ec2 (I guess that means local?)

**Comment by akoenig** [comment] 2018-02-13 12:08
Thanks @blocka for adding additional information. So that means you have the Prisma server running on an EC2 instance. Is that instance reachable via http://<your-host>:4466?

**Comment by blocka** [comment] 2018-02-13 12:10
Seems to be

**Comment by marktani** [comment] 2018-03-29 10:15
Thanks for bringing this up, I added it to #2018.

**Comment by do4gr** [comment] 2018-05-05 13:11
Hey, sorry for taking so long to get back about this. I just tried reproducing this on a fresh project and it did not get stuck. Could you try again with Prisma 1.7.1 and see whether you still have that problem?

**Comment by marktani** [comment] 2018-05-09 13:58
I'm closing this due to a missing reproduction, please create a new issue if you are experiencing this again 🙂

**Closed by marktani** 2018-05-09 13:58 UTC
Labels: area/deploy, kind/bug
