### ISSUE TITLE
Bug with self-relation?

### ISSUE THREAD

**Issue by alapini** [graphcool/prisma#1703] opened 2018-01-20 18:45 UTC
Self-relations don't seem to work properly in Prisma, but work fine in graphcool < 1.0 

**Current behavior**
```
Comment
    ✖ A relation directive for a self relation must appear either 1 or 2 times. Relation name: 'RelatedComments'  
    ✖ A relation directive for a self relation must appear either 1 or 2 times. Relation name: 'RelatedComments'
```

**Reproduction**
```bash
mkdir myproject && cd myproject
prisma init
```
`> Minimal setup: database-only`

Data model
```graphql
type Comment{
  id: ID! @unique
  title: String
  comments: [Comment!]! @relation(name: "RelatedComments")
  parent: Comment @relation(name: "RelatedComments")
}
```
```bash
prisma deploy
```

**Comment by mvaivre** [comment] 2018-01-22 08:36
Duplicate of https://github.com/graphcool/prisma/issues/1520

**Closed** 2018-01-28 14:31 UTC
Labels: kind/bug
