### ISSUE TITLE
`prisma deploy` hanging

### ISSUE THREAD

**Issue by hoodsy** [graphcool/prisma#1894] opened 2018-02-13 22:11 UTC
After making a minor change to my `schema`, I'm unable to run `prisma deploy`:

```

Deploying service `homeroom-api` to stage `dev` on cluster `public-specklechatter-107/prisma-us1`... 422ms

Changes:

  File (Type)
  + Created field `userPicture` of type `Relation`
  ~ Updated field `secret`. It is not required anymore.
  ~ Updated field `contentType`. It is not required anymore.

  User (Type)
  ~ Updated field `picture`. It is not required anymore.


Applying changes... (0/4)
Applying changes... (1/4)
```

I can work around this by first `prisma local nuke`, but I'd prefer to keep my testing data intact on `staging`. Also, I'd like to be able to handle this in a production environment.

Any ideas?

**Comment by hoodsy** [comment] 2018-02-14 14:39
I've tracked this down to be related to adding the `userPicture` relation – I'm unable to `deploy` with this relation, but I have no trouble deploying in a clean environment.

**Comment by marktani** [comment] 2018-02-14 14:39
Can you show the "before" and "after" schema?

**Comment by hoodsy** [comment] 2018-02-14 14:42
```graphql
type User {
  id: ID! @unique
  auth0Id: String! @unique
  stripeId: String @unique
  stripeCustomerId: String @unique
  email: String! @unique
  email_verified: String
  username: String! @unique
  name: String
  picture: File @relation(name: "UserPicture")

  # BEFORE
  # picture: String  
}

type File {
  id: ID! @unique
  name: String!
  secret: String @unique
  contentType: String
  createdAt: DateTime!
  updatedAt: DateTime!
  url: String! @unique
  userPicture: User @relation(name: "UserPicture")
}
```

I think I'm using `@relation` incorrectly as well – say I want to associate two `File` to one `User` – do I need to have two relation fields (e.g. `userPicture` and `userVideo` on `File`)?

**Comment by diogobeda** [comment] 2018-02-20 01:40
Same here, but I'm deploying to prisma cloud.
```graphql
# before
type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  firstName: String!
  lastName: String!
  households: [Household!]!
}

# after
# just adding the auth0id
type User {
  id: ID! @unique
  email: String! @unique
  auth0id: String! @unique
  password: String!
  firstName: String!
  lastName: String!
  households: [Household!]!
}
```

**Comment by medelman17** [comment] 2018-02-21 15:50
Was having the same problem. Try adding the new/additional field at the end of the existing fields in User ... For whatever reason, this works for me.

**Comment by marktani** [comment] 2018-02-22 09:40
@medelman17 can you also share the "before" and "after" schema? 🙂

**Comment by medelman17** [comment] 2018-02-22 15:30
Sure.  It was something like this: 

Old: 

`type User @model {
    id: ID! @unique
    createdAt: DateTime!
    updatedAt: DateTime!
    email: String! @unique
    password: String
    fb: String
    handle: String
    firstName: String
    middleName: String
    lastName: String
    address: [Address!]! @relation(name: "UserAddress" onDelete: CASCADE)
    phone: [Phone!]! @relation(name: "UserPhone" onDelete: CASCADE)
    clients: [User!]! @relation(name: "UserClients" onDelete: SET_NULL)
    colleague: [User!]! @relation(name: "UserColleagues" onDelete: SET_NULL)
}`

New: 

`type User @model {
    id: ID! @unique
    createdAt: DateTime!
    updatedAt: DateTime!
    email: String! @unique
    password: String
    uid: String! @unique 
    handle: String
    firstName: String
    middleName: String
    lastName: String
    address: [Address!]! @relation(name: "UserAddress" onDelete: CASCADE)
    phone: [Phone!]! @relation(name: "UserPhone" onDelete: CASCADE)
    clients: [User!]! @relation(name: "UserClients" onDelete: SET_NULL)
    colleague: [User!]! @relation(name: "UserColleagues" onDelete: SET_NULL)
}`

Might I also get a Prisma cloud beta invite?

**Comment by oliverjam** [comment] 2018-03-18 19:47
I'm getting the same thing trying to make a minor change to my schema. I went from

```gql
type User {
  id: ID! @unique
  name: String!
  email: String! @unique
  password: String!
  links: [Link!]!
  votes: [Vote!]!
}
```
to
```gql
type User {
  id: ID! @unique
  name: String!
  email: String! @unique
  githubId: String! @unique
  links: [Link!]!
  votes: [Vote!]!
}
```

`prisma deploy` output is:

```
Deploying service `hackernews-prisma` to stage `dev` on cluster `public-rosepuma-1/prisma-eu1` 137ms

Changes:

  User (Type)
  - Deleted field `password`
  + Created field `githubId` of type `String!`

Applying changes (10/2) ⣽
```

It hangs there indefinitely until I cancel the process.

**Comment by do4gr** [comment] 2018-05-07 16:46
Setting a  unique constraint will error if there are already duplicates present in the case of a field update or if a new field is required and unique since SQL will set default values for the newly required fields. I'm closing this issue since it seems to show symptoms of this problem. With the deploy changes from 1.6.1 and this PR the issue should be fixed https://github.com/graphcool/prisma/pull/2371 
If anyone is still experiencing problems please open a new issue with a reproduction.

**Closed** 2018-05-09 13:57 UTC
Labels: area/deploy, kind/bug
